name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Secrets は Settings > Secrets and variables > Actions に登録
      - name: Create production env file
        env:
          VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
          VITE_GA_ID: ${{ secrets.VITE_GA_ID }}
          VITE_GMAPS_BROWSER_KEY: ${{ secrets.VITE_GMAPS_BROWSER_KEY }}
        run: |
          echo "VITE_API_BASE=${VITE_API_BASE}" > .env.production
          echo "VITE_GA_ID=${VITE_GA_ID}" >> .env.production
          echo "VITE_GMAPS_BROWSER_KEY=${VITE_GMAPS_BROWSER_KEY}" >> .env.production

      - name: Build
        env:
          NODE_ENV: production
        run: npm run build

      # SPA 直リンク対策
      - name: SPA 404
        run: cp dist/index.html dist/404.html

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
